frr version 10.7.0-dev_git20260410
frr defaults traditional
hostname router2
!
interface eth1
    ip address 192.168.12.2/30
    mpls enable
    ip ospf network point-to-point
    link-params
!
interface eth2
    ip address 192.168.23.1/30
    mpls enable
    ip ospf network point-to-point
    link-params
!
interface eth3
    ip address 192.168.25.1/30
    mpls enable
    ip ospf network point-to-point
    link-params
!
interface lo
    ip address 10.0.0.2/32
    mpls enable
    link-params
!
router ospf
    ospf router-id 10.0.0.2
    ospf opaque-lsa
    !
    segment-routing on
    segment-routing global-block 16000 23999 local-block 15000 15999
    segment-routing prefix 10.0.0.2/32 index 2 no-php-flag
    !
    network 192.168.12.0/30 area 0
    network 192.168.23.0/30 area 0
    network 192.168.25.0/30 area 0
    network 10.0.0.2/32 area 0
    !
    mpls-te on
    mpls-te router-address 10.0.0.2
    mpls-te export
    exit
!
segment-routing
    traffic-eng
    exit
exit
!
line vty
