frr version 10.7.0-dev_git20260410
frr defaults traditional
hostname router1
!
interface eth1
    ip address 192.168.12.1/30
    mpls enable
    ip ospf network point-to-point

    ! Active les paramètres du lien (notamment pour configurer la bande passante max réservable)
    link-params
!
interface eth2
     ip address 192.168.14.1/30
     mpls enable
     ip ospf network point-to-point
     link-params
        max-rsv-bw 1.25e3
!
interface eth3
    ip address 192.168.13.1/30
    mpls enable
    ip ospf network point-to-point
    link-params
        max-rsv-bw 1.25e3
!
interface eth4
    ip address 192.168.10.1/30
    mpls enable
    ip ospf network point-to-point
    link-params
!
interface lo
    ip address 10.0.0.1/32
!
router ospf
    ospf router-id 10.0.0.1
    ospf opaque-lsa
    !
    segment-routing on
    segment-routing global-block 16000 23999 local-block 15000 15999
    segment-routing prefix 10.0.0.1/32 index 1 no-php-flag
    !
    network 192.168.12.0/30 area 0
    network 192.168.14.0/30 area 0
    network 192.168.13.0/30 area 0
    network 192.168.10.0/30 area 0
    network 10.0.0.1/32 area 0
    !
    mpls-te on
    mpls-te router-address 10.0.0.1
    mpls-te export
    exit
!
segment-routing
    traffic-eng
        mpls-te on
        mpls-te import ospfv2
        segment-list label_list
            index 2 mpls label 16002
            index 3 mpls label 16003
            index 4 mpls label 16004
            exit
        segment-list nai_list
            index 2 nai adjacency 192.168.12.1 192.168.12.2
            index 3 nai adjacency 192.168.23.1 192.168.23.2
            index 4 nai prefix 10.0.0.4/32 algorithm 0
            exit
        segment-list nai_list2
            index 2 nai adjacency 192.168.12.1 192.168.12.2
            index 4 nai prefix 10.0.0.4/32 algorithm 0
            exit
        pcep
            pce pce1
                address ip 172.20.20.10
                source-address ip 10.0.0.1
                exit
            pcc
                peer pce1
                exit
            exit
        exit
    exit
!
line vty

