frr version 10.7.0-dev_git20260410
frr defaults traditional
hostname router4
!
interface eth1
    ip address 192.168.34.2/30
    mpls enable
    ip ospf network point-to-point
    link-params
!
interface eth2
    ip address 192.168.14.2/30
    mpls enable
    ip ospf network point-to-point
    link-params
!
interface eth3
    ip address 192.168.54.2/30
    mpls enable
    ip ospf network point-to-point
    link-params
!
interface eth4
    ip address 192.168.40.1/30
    mpls enable
    ip ospf network point-to-point
    link-params
!
interface lo
    ip address 10.0.0.4/32
!
router ospf
    ospf router-id 10.0.0.4
    ospf opaque-lsa
    !
    segment-routing on
    segment-routing global-block 16000 23999 local-block 15000 15999
    segment-routing prefix 10.0.0.4/32 index 4 no-php-flag
    !
    network 192.168.34.0/30 area 0
    network 192.168.14.0/30 area 0
    network 192.168.54.0/30 area 0
    network 192.168.40.0/30 area 0
    network 10.0.0.4/32 area 0
    !
    mpls-te on
    mpls-te router-address 10.0.0.4
    mpls-te export
    exit
!
segment-routing
    traffic-eng
        mpls-te on
        mpls-te import ospfv2
        pcep
            pce pce1
                address ip 172.20.20.10
                source-address ip 10.0.0.4
                exit
            pcc
                peer pce1
                exit
            exit
        exit
    exit
!
line vty
